services:
  npm-sync:
    image: npm-sync:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: npm-sync
    env_file:
      - .env
    volumes:
      - ./config:/config:ro
    restart: "no"
